import {
  addCleanupTarget,
  alternativeCleanup,
  buildCleanupTargets,
  cleanupDirectoryWithRetry,
  getAlternativeCleanupExecutor,
  isWithinManagedProjectsRoot,
  makeDirectoryWritable,
  manualRecursiveRemoval,
  resetAlternativeCleanupExecutor,
  resetCleanupDirectoryExecutor,
  resetMakeDirectoryWritableExecutor,
  resetManualRecursiveRemovalExecutor,
  setAlternativeCleanupExecutor,
  setCleanupDirectoryExecutor,
  setMakeDirectoryWritableExecutor,
  setManualRecursiveRemovalExecutor,
  getMakeDirectoryWritableExecutor,
  getManualRecursiveRemovalExecutor
} from './cleanup.js';
import {
  applyExtraProtectedPids,
  buildLogEntries,
  buildProcessKeyCandidates,
  buildProcessState,
  ensureDefaultHostPort,
  ensurePortsFreed,
  findPidsByPort,
  findPidsByPortUnix,
  findPidsByPortWindows,
  findProjectByIdentifier,
  deriveProjectPorts,
  getExecCommandImpl,
  getExecFileImpl,
  getPlatformImpl,
  getProjectFrameworks,
  getProjectPortHints,
  getRunningProcessEntry,
  getStoredProjectPorts,
  hasLiveProcess,
  hostReservedPorts,
  isPidActive,
  isProtectedPid,
  killProcessesOnPort,
  killProcessTree,
  logProtectedPidSkip,
  normalizeProcessEntry,
  normalizeProcessKey,
  parsePidList,
  protectedPidSet,
  resetPlatformOverride,
  resetExecCommandOverride,
  resetExecFileOverride,
  resolveActivityState,
  resolveLastKnownPort,
  resolveTerminationProject,
  runningProcesses,
  sanitizeProcessSnapshot,
  setExecCommandOverride,
  setExecFileOverride,
  setPlatformOverride,
  storeRunningProcesses,
  terminateRunningProcesses
} from './processManager.js';
import {
  attachTestErrorDetails,
  buildFileTree,
  buildProjectUpdatePayload,
  extractFileContentFromRequest,
  isUnsafeRelativePath,
  normalizeRepoPath,
  resetFsModuleOverride,
  resolveProjectRelativePath,
  setFsModuleOverride
} from './internals.js';

export { killProcessesOnPort, killProcessTree, findPidsByPort, isProtectedPid, cleanupDirectoryWithRetry };

export const __processManager = {
  killProcessesOnPort,
  killProcessTree,
  findPidsByPort,
  isProtectedPid,
  ensurePortsFreed
};

export const __projectRoutesInternals = {
  setCleanupDirectoryExecutor,
  resetCleanupDirectoryExecutor,
  setAlternativeCleanupExecutor,
  resetAlternativeCleanupExecutor,
  getAlternativeCleanupExecutor,
  setFsModuleOverride,
  resetFsModuleOverride,
  isWithinManagedProjectsRoot,
  addCleanupTarget,
  buildCleanupTargets,
  attachTestErrorDetails,
  cleanupDirectoryWithRetry,
  alternativeCleanup,
  normalizeRepoPath,
  isUnsafeRelativePath,
  resolveProjectRelativePath,
  setManualRecursiveRemovalExecutor,
  resetManualRecursiveRemovalExecutor,
  getManualRecursiveRemovalExecutor,
  manualRecursiveRemoval,
  makeDirectoryWritable,
  setMakeDirectoryWritableExecutor,
  resetMakeDirectoryWritableExecutor,
  getMakeDirectoryWritableExecutor,
  setExecCommandOverride,
  resetExecCommandOverride,
  getExecCommandImpl,
  setExecFileOverride,
  resetExecFileOverride,
  getExecFileImpl,
  setPlatformOverride,
  resetPlatformOverride,
  getPlatformImpl,
  buildProcessState,
  normalizeProcessEntry,
  isPidActive,
  normalizeProcessKey,
  buildProcessKeyCandidates,
  storeRunningProcesses,
  getRunningProcessEntry,
  getRunningProcessesStore: () => runningProcesses,
  resetRunningProcessesStore: () => runningProcesses.clear(),
  findProjectByIdentifier,
  deriveProjectPorts,
  getStoredProjectPorts,
  hasLiveProcess,
  buildLogEntries,
  getProjectFrameworks,
  getProjectPortHints,
  resolveLastKnownPort,
  resolveActivityState,
  sanitizeProcessSnapshot,
  resolveTerminationProject,
  buildProjectUpdatePayload,
  extractFileContentFromRequest,
  ensureDefaultHostPort,
  applyExtraProtectedPids,
  logProtectedPidSkip,
  getProtectedPidSet: () => protectedPidSet,
  getHostReservedPorts: () => hostReservedPorts,
  parsePidList,
  findPidsByPortWindows,
  findPidsByPortUnix,
  findPidsByPort,
  ensurePortsFreed,
  killProcessesOnPort,
  killProcessTree,
  buildFileTree,
  terminateRunningProcesses
};
